#!/bin/bash
# A recommended daily cronjob for subtitle maintenance
# e.g.:
# 13 0 * * * ~/.local/bin/subs-cronjob >~/.last-subs-cron-job 2>&1

# NOTE: cron messes with the PATH; assuming this script is in
#  the subshop directory, add the script's directory to the PATH
#  to pick up 'subshop'.
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
PATH="$PATH:${SCRIPT_DIR}"
export PATH

set -x
    # update the todo list
subshop todo
    # try to download/sync subs for new videos (<30 days) AND a random selection
subshop dos --todo
    # try to fix poorly scored subs
subshop redos --todo
    # try to download reference files for videos lacking them
subshop ref --todo
